version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    hostname: postgres
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Subasta-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: -p 5433
    restart: unless-stopped
  subasta-app:
    image: subasta-dev
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - postgres-data:/app/postgres-data
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5433/Subasta-dev?schema=public
    ports:
      - 3000:3000
volumes:
  postgres-data: