version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Subasta
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: -p 5433
    restart: unless-stopped
  subasta-app:
    image: subasta
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/app/postgres-data
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5433/Subasta?schema=public
    ports:
      - 3000:3000
volumes:
  postgres-data: